// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQnU9ODlp6XxCjHEY2MG3j5ycYyf1DOoM',
    appId: '1:184662057440:web:e347deaf07b74ea0d3cb85',
    messagingSenderId: '184662057440',
    projectId: 'flutter-study-c613a',
    authDomain: 'flutter-study-c613a.firebaseapp.com',
    storageBucket: 'flutter-study-c613a.appspot.com',
    measurementId: 'G-BM29V19NLY',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfSc8H6JmAtrDeawPa7ontjqFwvr9FQfU',
    appId: '1:184662057440:ios:ffe4053b6b7370e6d3cb85',
    messagingSenderId: '184662057440',
    projectId: 'flutter-study-c613a',
    storageBucket: 'flutter-study-c613a.appspot.com',
    iosClientId: '184662057440-dgos8mblhllv63386gksqfemuhdsppmq.apps.googleusercontent.com',
    iosBundleId: 'com.inbeom.fluttagram',
  );
}
